spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/fleet-driver-service
#    username: root
#    password: root  
  
  jpa:
    show-sql: true
    generate-ddl: true
    
springdoc:
  swagger-ui:
    enabled: true
    path: /driver-service-doc.html
  api-docs:
    enabled: true
    path: /driver-service-api

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
    fetch-registry: true
    register-with-eureka: true

#disable this if eureka was there and 
#programatically enabling the ribbon
#ribbon:
#  eureka:
#    enabled: false
    
#vehicle-service: 
#  ribbon: 
#    listOfServers: localhost:9191,localhost:9193
    