spring:
  application:
    name: fleet-management-gateway

server:
  port: 8095
  
zuul:
  prefix: /gateway
  
  routes:
    #driver-management-service:
    fleet-driver-service:
      service-id: fleet-driver-service
      path: /fleet-driver-service/**
    vehicle-management-service:
      service-id: vehicle-management-service
      path: /vehicle-management-service/**
