spring:
  application:
    name: vehicle-management-service
  #profiles:
    #active:
    #- dev

  cloud:
    config:
      profile: stage
  rabbitmq:
    host: grouse.rmq.cloudamqp.com
    virtual-host: ddfrrrdd
    username: ddfrrrdd
    password: 5w8gTwhmnVKTUPr5bW04XV5D_d-HeaJ2

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 9193
    
      