spring:
  application:
    name: fleet-management-gateway
  cloud:
    gateway:
      routes:
      - id: vehicle-management-service
        uri: http://localhost:9193/
        predicates:
        - Path=/vehicle/**
      - id: vehicle-management-service2
        uri: http://localhost:9193/
        predicates:
        - Path=/vehicle/**
      - id: fleet-driver-service
        uri: http://localhost:9092/
        predicates:
        - Path=/api/driver/**
      discovery:
        locator:
          enabled: true
          
                  
server:
  port: 8095
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging: 
  level: 
    org: 
     springframework: 
       cloud: 
         gateway: TRACE
  
